### ISSUE TITLE
Oracle sql generator error

### ISSUE THREAD

**Issue by wacav** [vuerd/vuerd#112]
COLUMN NUMBER    NOT NULL DEFAULT 1                    // it's error
COLUMN NUMBER    DEFAULT 1 NOT NULL                    // it's works

**Comment by wacav** [comment]
> COLUMN NUMBER NOT NULL DEFAULT 1 // it's error
> COLUMN NUMBER DEFAULT 1 NOT NULL // it's works

use oracle 11g

**Comment by dineug** [comment]
Thanks for letting me know!

**Comment by wacav** [comment]
Thanks you!
