### ISSUE TITLE
Crow's foot notation: Cardinality

### ISSUE THREAD

**Issue by simeonlin** [vuerd/vuerd#157]
There is still a open point with the crowfoot notation. (see my already resolved issue at (https://github.com/vuerd/vuerd-vscode/issues/8))

According Wikipedia there are only four types of cardinalities that an entity may have in a relationship:
ring and dash → minimum zero, maximum one (optional)
dash and dash → minimum one, maximum one (mandatory)
ring and crow's foot → minimum zero, maximum many (optional)
dash and crow's foot → minimum one, maximum many (mandatory)

But vuerd is still showing Cardinality with only one dash and is missing to show the information, if the relationship is mandatory on the other side or not by showing an addional dash or an additional ring.

Example: The relationship iteself is not showing, if a comment must have a blog or not:
![image](https://user-images.githubusercontent.com/46026544/91634879-2a592a00-e9f4-11ea-9e7d-b8c72ef2a977.png)

**Comment by dineug** [comment]
I don't really know what the problem is.

Because the tools that I used or I used to use were similar.

ex)
[erdcloud](https://www.erdcloud.com/)
[workbench](https://www.mysql.com/products/workbench/design/)
[eXERD](http://en.exerd.com/)

**Comment by simeonlin** [comment]
No, identification is fine in my view.

An example from the MySQL-Workbench:
![image](https://user-images.githubusercontent.com/46026544/91689133-c5bcdd00-eb63-11ea-8113-fd05642bbea8.png)

The two dashes are indicating that the city must have a country.
Other option would be: If the country on the city is optional, then there would be a 'ring and dash' instead of 'dash and dash'.

For me, this is the most important open issue with the crow's foot notation.

According to this, vuerd let you choose some other improper cardinalities when you create a relationship:

![image](https://user-images.githubusercontent.com/46026544/91690043-8ee7c680-eb65-11ea-98cb-f5f0021bb00b.png)

Does this clear out my point?

Keep up tho good work! 👏

**Comment by dineug** [comment]
It's been reflected in the latest version.
Thank you!

**Comment by simeonlin** [comment]
Great!!
There is just one problem left.
The icon is not changing with the NULL/NOT NULL information of the forein key column.

When the foreign key column is N-N (NOT NULL) the icon on the other side should be Ring and Dash and not Dash and Dash:
![image](https://user-images.githubusercontent.com/46026544/114354296-4f0ea600-9b6e-11eb-98dd-3c5c5e073af1.png)

Should I open a new issue for this?
(Sorry for messing around with this details. I would love to use your tool in the database courses I teach, and it is really important that the students learn the propper notification. 😃 )

**Comment by dineug** [comment]
Thanks for letting me know!
<img width="83" alt="r-nn" src="https://user-images.githubusercontent.com/45829489/114424057-bb32ed80-9bf2-11eb-894d-f803e8b8f12f.png">

**Comment by simeonlin** [comment]
Yes, that's it! Thank you so much! 👏 👏 👍
