### ISSUE TITLE
Zoom in ERD view?

### ISSUE THREAD

**Issue by adsee42** [vuerd/vuerd#175]
Great tool!

But on my small screen, only 5 or 6 tables are visible, others are outside the screen.
A zoom feature would be very helpful.

**Comment by alan-jupitaka** [comment]
What a great tool it is. 

But It seems to need to zoom in/out.

It would be really helpful. 

Thank you.

**Comment by dineug** [comment]
It was a function I wanted to put in.

But I'm having a hard time implementing the mini-map calculation formula, so I can't.

At the zoom level, I'll think about removing the mini map and operating it!

**Comment by dineug** [comment]
here #183

**Comment by adsee42** [comment]
That looks amazing!!
Can't wait for v2 release
