### ISSUE TITLE
The AUTO ICREMENT on postgres is missing.

### ISSUE THREAD

**Issue by grobbles** [vuerd/vuerd#189]
Hi, 
your tool is very nice and helpful but when generating the PostgreSQL DDL text the automatic incrementation of the primary key is missing. The Auto Increment button has no effect on PostgreSQL.

I miss the following expression:
```
CREATE TABLE public."table"
(
    id integer NOT NULL **GENERATED ALWAYS AS IDENTITY**
);
```

**Comment by dineug** [comment]
I recommend using that type.
- SERIAL
- BIGSERIAL
