### ISSUE TITLE
Layout arrangement option

### ISSUE THREAD

**Issue by JuanEL0** [vuerd/vuerd#192]
Hi, 

This tool is really cool and I love using it in VsCode.

This is more of a visual suggestion, it would be nice if there was an option to arrange (or rearrange) the diagram to see all relationships when the database is too big.

Currently, it shows all relationships but it is not posible to understand all the relations at a glance.

![Captura de Pantalla 2021-04-20 a la(s) 12 14 04](https://user-images.githubusercontent.com/64238991/115437526-e8befe80-a1d1-11eb-9a21-206890e25178.png)

**Comment by dineug** [comment]
vcode extension v0.9.8 has been reflected.
