### ISSUE TITLE
Create relationships between existing columns

### ISSUE THREAD

**Issue by PhucNgo1711** [vuerd/vuerd#203]
From the UI, can you create a relationship between 2 existing "non-id" columns? 

For example, I have a `Vehicle` table with 2 columns
```
VehicleID - pk
VIN
```
And a `Sales` table with 2 columns
```
SaleID - pk
VIN
```

Is it possible to create a relationship between the 2 tables using the `VIN` column?

**Comment by dineug** [comment]
That's impossible.

You can take a detour in the following way.

<img width="374" alt="스크린샷 2021-06-24 오후 1 33 31" src="https://user-images.githubusercontent.com/45829489/123203180-e8542400-d4f0-11eb-8462-92aab52b7c84.png">
<img width="369" alt="스크린샷 2021-06-24 오후 1 33 54" src="https://user-images.githubusercontent.com/45829489/123203197-ef7b3200-d4f0-11eb-8f5a-4ffe245cbf6c.png">
<img width="364" alt="스크린샷 2021-06-24 오후 1 34 05" src="https://user-images.githubusercontent.com/45829489/123203207-f3a74f80-d4f0-11eb-9c2b-852a70b7a037.png">

**Comment by PhucNgo1711** [comment]
I see. Thanks!
