### ISSUE TITLE
How to remove some navbar panel options?

### ISSUE THREAD

**Issue by AdrianLsk** [vuerd/vuerd#205]
Hello, how can I remove some of the default navbar options?

I would like to keep only a few.

**Comment by dineug** [comment]
There's no current function.
Let me add the ignorePanels option.

Or

You can create a custom build by removing it directly from the [file](https://github.com/vuerd/vuerd/blob/d5f536db828e0f55a7b5b76a7505ac4513937aa4/packages/vuerd/src/extensions/builtin.ts#L9).

**Comment by AdrianLsk** [comment]
Hi, sorry for the late response.

That would be fantastic if you included the option to ignore panels in the panel settings. It's more efficient and useful for others as well, instead of rebuilding it myself.

**Comment by dineug** [comment]
```js
// vuerd^2.2.4
extension({
  excludePanel: [/^@vuerd/]
});
```

**Comment by AdrianLsk** [comment]
Perfect, thanks a lot!
