### ISSUE TITLE
Code that automatically arranges tables

### ISSUE THREAD

**Issue by AdrianLsk** [vuerd/vuerd#206]
Hi, can you please point me to the code that calculates the automatic layout of tables?

**Comment by dineug** [comment]
If it's about table alignment, [here](https://github.com/vuerd/vuerd/blob/d5f536db828e0f55a7b5b76a7505ac4513937aa4/packages/vuerd/src/engine/command/table.cmd.ts#L133) it is.

**Comment by AdrianLsk** [comment]
Perfect, thank you!
