### ISSUE TITLE
[Request] Default values to table

### ISSUE THREAD

**Issue by peterstriz** [vuerd/vuerd#214]
Add a simple button when table is empty (only if table is empty, else it will disappear) to add boilerplate: `Id` (Integer, with PK and Auto Inc.), `Created_at` (timestamp), `Updated_at` (timestamp)

<img src="https://user-images.githubusercontent.com/43370218/126328176-c21d6bde-89d2-421f-9145-00568be7aef4.png" width="400">

**Comment by dineug** [comment]
Basically, I want to take simple UI configuration.
I don't think we need a repetitive column because it can be copied from another table.

**Comment by dineug** [comment]
Move table context menu.
<img width="471" alt="스크린샷 2021-07-27 오후 9 36 18" src="https://user-images.githubusercontent.com/45829489/127154799-bff69b53-146a-4ab6-811f-de46795e5450.png">
