### ISSUE TITLE
VSCode: Import/Export functionality

### ISSUE THREAD

**Issue by luckcolors** [vuerd/vuerd#236]
Hello.
Thanks for making this tool.
I've been looking for something like this for a good while and i can't streess enough how it is helping me. 😄 

I wanted to report that there's some weird behaviour with the import/export buttons.

Export:
 - Uses vscode form, but defaults to my user home. I would suggest that instead. See [link](https://code.visualstudio.com/docs/editor/variables-reference), if a project folder is open it should default to the root of that folder or missing that use the base path of the .vuerd file we're editing (or maybe always use this ?).
 
 This is not really a bug per se, but i'm sure the case can be made that it is a better default as in most situations it would point to a path near to where you actually want to save/load things.
 
 Import:
 - All import buttons open the webview default file browser, wich would be fine if files were always local.
   But for example if you're using something likes SSHFS or RemoteDEV extension you can't really point the WebView file browser to that file since it doesn't exist on the machine.
   This would need to be done with the vscode form like the export.

Let me know what you think of this, i unfortunately don't have much experience with working with VSCode extension development but if it is easy enough i could help with the pull request.
Thank you again.

**Comment by dineug** [comment]
I modified the Export based on the workspace folder you told me about.
Thanks for letting me know!

The import seems to need two cases.

1. local file dialog
2. remote file dialog

It's simple if you only support one thing in remote mode.
If apply for all, it is cumbersome to maintain vuerd.

[file].vuerd, [file].vuerd.json can be opened directly from a remote location.
Is remote remote remote file dialog required?

**Comment by luckcolors** [comment]
> 
> 
> I modified the Export based on the workspace folder you told me about.
> Thanks for letting me know!
>
No problem, thank you for the work. 😄 

> The import seems to need two cases.
> 
>     1. local file dialog
> 
>     2. remote file dialog
> 
Well, as i said the vscode file form already abstracts this away for you, i suppose you could check if the page is in vscode and then call the right form? Maybe an new setting variable could help with this?

> [file].vuerd, [file].vuerd.json can be opened directly from a remote location.
> Is remote file dialog required?
For this no. It's only required for the import SQL/json functionality.

**Comment by dineug** [comment]
Okay.
I'll change the import to use vcode dialog.

**Comment by dineug** [comment]
vcode extension v0.9.6 has been reflected.

**Comment by luckcolors** [comment]
Thank you!
It seems to work.

However when importing a single table it seems to completely the entire sheet?
Is this intended?
Any way i can import in a append fashion?

**Comment by dineug** [comment]
Yes, thank you

**Comment by luckcolors** [comment]
Will do. 😄
