### ISSUE TITLE
Automatic foreign key assignment

### ISSUE THREAD

**Issue by raindata5** [vuerd/vuerd#255]
Good Afternoon! Today is my second day using the ERD and I'm loving it so far. Nice work man!
Now there is one little issue I'm running into and I'm not sure if it's just me or not.
When I go to assign a foreign key the ERD keeps automatically mapping it to a random column in another table that I choose. And I'm not allowed to adjust the column it maps to. Is this normal or could be there some option that I have to enable?

**Comment by dineug** [comment]
It's a normal function.
The order of designation is as follows.

<img width="474" alt="스크린샷 2021-11-24 오전 9 24 32" src="https://user-images.githubusercontent.com/45829489/143149453-effa15d4-8fc4-403a-8d8f-ca0f26dff1df.png">


<img width="420" alt="스크린샷 2021-11-24 오전 9 26 02" src="https://user-images.githubusercontent.com/45829489/143149492-70108905-1bd9-424a-85f9-1956e63c3545.png">

**Comment by raindata5** [comment]
😅 ahh ok now I see lol. It's weird because I thought I was doing that yesterday but after all it was a long day haha. Thanks for the timely response man really appreciate it 👍!
