### ISSUE TITLE
Exporting to image crops of the sides in VS code for MAC

### ISSUE THREAD

**Issue by benedikt-buchert** [vuerd/vuerd#256]
Thanks for building this it's a great tool. I found a Bug where,
exporting an image 3000x3000px the exported area is not correctly centered and parts of the image are cropped.

**Comment by benedikt-buchert** [comment]
Only when zooming out the whole area is visible.

**Comment by benedikt-buchert** [comment]
It seems to be depending on the viewport. If I have the section in the upper left corner opened it exports the full image.

**Comment by dineug** [comment]
I think it'll help if there's an image of a case that cuts off.

**Comment by benedikt-buchert** [comment]
[[](url)](https://imgur.com/a/CFUKxtp)

**Comment by dineug** [comment]
Thank you. It helped me solve the problem.

**Comment by benedikt-buchert** [comment]
Wow you are amazing! Will test the fix on Monday.

**Comment by benedikt-buchert** [comment]
Sorry for the late response I just tested and it seems to work like a charm.

**Comment by benedikt-buchert** [comment]
Thank you!
