### ISSUE TITLE
Can't paste or type new DDL

### ISSUE THREAD

**Issue by JonFranchi** [vuerd/vuerd#4]
I really liked what I saw in the images here and I was looking at this tool as something where I might be able to script the build of a new ERD for each migration and use those to manually build plans for new migrations.

The issue I'm having is that I can't seem to type anything into the SQL tab  If I create a tab from the GUI it will appear with syntax highlighting but if I type the exact same statement its just plain white letters, no syntax highlighting, and it doesn't render anything based on my inputs. 

Is this expected behavior?  Are we just not there yet in the development of this package?

**Comment by dineug** [comment]
No editing function exists because the SQL tab only displays SQL DDL generation.

Only ERD and Grid can edit.

SQL DDL import is:
It's in ERD Contextmenu(Right-click).
