### ISSUE TITLE
Menu options not working on click while using with LitElement.

### ISSUE THREAD

**Issue by NadeemShakya** [vuerd/vuerd#41]
Hi,
In my case, I'm using this library with `LitElement`.
Everything works as expected, but I cannot seem to click the menu options (the one that appears after I right-click the canvas). 

#### Whenever I click on any of these menu options, nothing happens:

![image](https://user-images.githubusercontent.com/32034842/84001204-dc4d0100-a985-11ea-8b65-72264c8e8ebb.png)

##### My understanding

Also, when I used the chunk of code provided from *CDN Quickstart* in vanilla JS, everything worked as expected. I think there's some issue because of the shadow DOM.

**Comment by dineug** [comment]
Thanks for letting me know.
That bug is my mistake!
