### ISSUE TITLE
Cannot find any information on Real-time simultaneous editing API.

### ISSUE THREAD

**Issue by NadeemShakya** [vuerd/vuerd#42]
Hey, 
I am having a scenario where multiple users will be editing the same ER diagram. So, I'm working on to update real-time data for those multiple users.

I have tried `polling` to achieve this and works as I want it to work.

I've found out that you have provided support for **Real-time simultaneous editing API**, but I couldn't find any detailed documentation about it. Can you provide me a link(or any resource) for the **Real-time simultaneous editing API** feature?

**Comment by dineug** [comment]
Document is [here](https://vuerd.github.io/vuerd/?path=/story/editor--share)

```javascript
editor.sharePull((commands) => {
  // your send websocket -> commands data
  socket.emit('my other event', {
    commands
  });
});

socket.on('my other event', function (data) {
  editor.sharePush(data.commands);
});
```

**Comment by NadeemShakya** [comment]
Thanks for the quick response. :+1:
